spring:
  application:
    name: "apigateway"

  config:
    import: "optional:configserver:http://localhost:8071/"

#We need to tell our gateway server, please connect with discovery server(Eureka server)
# levarage the information present there(all details about the microservices)
# to forward all the requests that are coming from external clients. To provide the same
#information we need to add cloud property here under spring
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
#configuration to enable gateway related endpoints inside the actuator:
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true



info:
  app:
    name: "gatewayserver"
    description: "blah blah api-gateway application"
    version: "1.0"